package com.codecool.termlib;

import java.util.Random;

class Words {
	private static String regularWords = "NAME VERY THROUGH JUST FORM MUCH GREAT THINK SAY HELP LOW LINE BEFORE TURN CAUSE SAME MEAN DIFFER MOVE RIGHT BOY OLD TOO DOES TELL SENTENCE SET THREE WANT AIR WELL ALSO PLAY SMALL END PUT HOME READ HAND PORT LARGE SPELL ADD EVEN LAND HERE MUST BIG HIGH SUCH FOLLOW ACT WHY ASK MEN CHANGE WENT LIGHT KIND OFF NEED HOUSE PICTURE TRY US AGAIN ANIMAL POINT MOTHER WORLD NEAR BUILD SELF EARTH FATHER HEAD STAND OWN PAGE SHOULD COUNTRY FOUND ANSWER SCHOOL GROW STUDY STILL LEARN PLANT COVER FOOD SUN FOUR THOUGHT LET KEEP EYE NEVER LAST DOOR BETWEEN CITY TREE CROSS SINCE HARD START MIGHT STORY SAW FAR SEA DRAW LEFT LATE RUN WHILE PRESS CLOSE NIGHT REAL LIFE FEW STOP";


/**
getWord() method pick a random word from from a private instance, and return it as a string.
*/
	public static String getWord() {
		String[] arrWords = regularWords.split(" ");
		Random r = new Random();
		int randomNumber = r.nextInt(arrWords.length);
		return arrWords[randomNumber];
	}
}
